#############
# Format
## Armour (inc. shields & cloak)
# [<slot>.<heavy/medium/light>.<rarity>]
# <stat> = [<new gear value>, <maxed value>]
## Weapon
# [<melee/bow/staff>.<type>.<rarity>]
# <stat> = [<new gear value>, <maxed value>]
#
# Tips
# If you're trying to find something, search for it!
#############

# Head
## Heavy
[head.heavy.rare]
armour = [27, 37]
magic = [25, 35]
str = [19, 25]
dex = [0]
int = [0]
vit = [18, 23]

[head.heavy.epic]
armour = [28, 38]
magic = [26, 36]
str = [20, 26]
dex = [0]
int = [0]
vit = [19, 25]

[head.heavy.legendary]
armour = [30, 40]
magic = [24, 34]
str = [24, 31]
dex = [0]
int = [0]
vit = [15, 20]

## Medium
[head.medium.rare]
armour = [24, 34]
magic = [22, 32]
str = [0]
dex = [19, 25]
int = [0]
vit = [16, 21]

[head.medium.epic]
armour = [25, 35]
magic = [23, 33]
str = [0]
dex = [20, 26]
int = [0]
vit = [17, 22]

[head.medium.legendary]
armour = [27, 37]
magic = [21, 31]
str = [0]
dex = [24, 31]
int = [0]
vit = [14, 18]

## Light
[head.light.rare]
armour = [21, 31]
magic = [19, 29]
str = [0]
dex = [0]
int = [19, 25]
vit = [12, 16]

[head.light.epic]
armour = [22, 32]
magic = [20, 30]
str = [0]
dex = [0]
int = [20, 26]
vit = [12, 16]

[head.light.legendary]
armour = [24, 34]
magic = [20, 30]
str = [0]
dex = [0]
int = [24, 31]
vit = [13, 17]

# Shoulders
## Heavy
[shoulders.heavy.rare]
armour = [27, 37]
magic = [25, 35]
str = [19, 25]
dex = [0]
int = [0]
vit = [18, 23]

[shoulders.heavy.epic]
armour = [28, 38]
magic = [26, 36]
str = [20, 26]
dex = [0]
int = [0]
vit = [19, 25]

[shoulders.heavy.legendary]
armour = [30, 40]
magic = [24, 34]
str = [24, 31]
dex = [0]
int = [0]
vit = [15, 20]

## Medium
[shoulders.medium.rare]
armour = [24, 34]
magic = [22, 32]
str = [0]
dex = [19, 25]
int = [0]
vit = [16, 21]

[shoulders.medium.epic]
armour = [25, 35]
magic = [23, 33]
str = [0]
dex = [19, 25]
int = [0]
vit = [16, 21]

[shoulders.medium.legendary]
armour = [27, 37]
magic = [21, 31]
str = [0]
dex = [24, 31]
int = [0]
vit = [14, 18]

## Light
[shoulders.light.rare]
armour = [21, 31]
magic = [19, 29]
str = [0]
dex = [0]
int = [19, 25]
vit = [12, 16]

[shoulders.light.epic]
armour = [22, 32]
magic = [20, 30]
str = [0]
dex = [0]
int = [20, 26]
vit = [12, 16]

[shoulders.light.legendary]
armour = [24, 34]
magic = [20, 30]
str = [0]
dex = [0]
int = [24, 31]
vit = [13, 17]

# Chest
## Heavy
[chest.heavy.rare]
armour = [27, 37]
magic = [23, 33]
str = [20, 26]
dex = [0]
int = [0]
vit = [19, 25]

[chest.heavy.epic]
armour = [28, 38]
magic = [24, 34]
str = [21, 27]
dex = [0]
int = [0]
vit = [18, 23]

[chest.heavy.legendary]
armour = [30, 40]
magic = [24, 34]
str = [25, 33]
dex = [0]
int = [0]
vit = [24, 31]

## Medium
[chest.medium.rare]
armour = [24, 34]
magic = [20, 30]
str = [0]
dex = [20, 26]
int = [0]
vit = [17, 22]

[chest.medium.epic]
armour = [25, 35]
magic = [21, 31]
str = [0]
dex = [21, 27]
int = [0]
vit = [18, 23]

[chest.medium.legendary]
armour = [27, 37]
magic = [21, 31]
str = [0]
dex = [25, 33]
int = [0]
vit = [23, 30]

## Light
[chest.light.rare]
armour = [21, 31]
magic = [17, 27]
str = [0]
dex = [0]
int = [20, 26]
vit = [16, 21]

[chest.light.epic]
armour = [22, 32]
magic = [18, 28]
str = [0]
dex = [0]
int = [21, 27]
vit = [17, 22]

[chest.light.legendary]
armour = [24, 34]
magic = [20, 30]
str = [0]
dex = [0]
int = [25, 33]
vit = [22, 29]

# Gloves
## Heavy
[gloves.heavy.rare]
armour = [24, 34]
magic = [21, 31]
str = [18, 23]
dex = [0]
int = [0]
vit = [18, 23]

[gloves.heavy.epic]
armour = [25, 35]
magic = [22, 32]
str = [19, 25]
dex = [0]
int = [0]
vit = [20, 26]

[gloves.heavy.legendary]
armour = [28, 38]
magic = [22, 32]
str = [19, 25]
dex = [0]
int = [0]
vit = [17, 22]

## Medium
[gloves.medium.rare]
armour = [20, 30]
magic = [18, 28]
str = [0]
dex = [18, 23]
int = [0]
vit = [16, 21]

[gloves.medium.epic]
armour = [21, 31]
magic = [19, 29]
str = [0]
dex = [19, 25]
int = [0]
vit = [18, 23]

[gloves.medium.legendary]
armour = [21, 31]
magic = [19, 29]
str = [0]
dex = [19, 25]
int = [0]
vit = [16, 21]

## Light
[gloves.light.rare]
armour = [17, 27]
magic = [15, 25]
str = [0]
dex = [0]
int = [18, 23]
vit = [10, 13]

[gloves.light.epic]
armour = [18, 28]
magic = [16, 26]
str = [0]
dex = [0]
int = [19, 25]
vit = [10, 13]

[gloves.light.legendary]
armour = [18, 28]
magic = [16, 26]
str = [0]
dex = [0]
int = [19, 25]
vit = [15, 20]

# Legs
## Heavy
[legs.heavy.rare]
armour = [27, 37]
magic = [23, 33]
str = [20, 26]
dex = [0]
int = [0]
vit = [19, 25]

[legs.heavy.epic]
armour = [28, 28]
magic = [24, 34]
str = [21, 27]
dex = [0]
int = [0]
vit = [20, 26]

[legs.heavy.legendary]
armour = [30, 40]
magic = [24, 34]
str = [25, 33]
dex = [0]
int = [0]
vit = [24, 31]

## Medium
[legs.medium.rare]
armour = [24, 34]
magic = [20, 30]
str = [0]
dex = [21, 27]
int = [0]
vit = [17, 22]

[legs.medium.epic]
armour = [25, 35]
magic = [21, 31]
str = [0]
dex = [21, 27]
int = [0]
vit = [23, 30]

[legs.medium.legendary]
armour = [27, 37]
magic = [21, 31]
str = [0]
dex = [25, 33]
int = [0]
vit = [23, 30]

## Light
[legs.light.rare]
armour = [21, 31]
magic = [17, 27]
str = [0]
dex = [0]
int = [20, 26]
vit = [16, 21]

[legs.light.epic]
armour = [22, 32]
magic = [18, 28]
str = [0]
dex = [0]
int = [21, 27]
vit = [17, 22]

[legs.light.legendary]
armour = [24, 34]
magic = [20, 30]
str = [0]
dex = [0]
int = [25, 33]
vit = [22, 29]

# Shoes
## Heavy
[shoes.heavy.rare]
armour = [24, 34]
magic = [21, 31]
str = [18, 23]
dex = [0]
int = [0]
vit = [18, 23]

[shoes.heavy.epic]
armour = [25, 35]
magic = [22, 32]
str = [19, 25]
dex = [0]
int = [0]
vit = [20, 26]

[shoes.heavy.legendary]
armour = [28, 38]
magic = [22, 32]
str = [19, 25]
dex = [0]
int = [0]
vit = [17, 22]

## Medium
[shoes.medium.rare]
armour = [20, 30]
magic = [18, 28]
str = [0]
dex = [18, 23]
int = [0]
vit = [18, 23]

[shoes.medium.epic]
armour = [21, 31]
magic = [19, 29]
str = [0]
dex = [19, 25]
int = [0]
vit = [20, 26]

[shoes.medium.legendary]
armour = [21, 31]
magic = [19, 29]
str = [0]
dex = [19, 25]
int = [0]
vit = [16, 21]

## Light
[shoes.light.rare]
armour = [17, 27]
magic = [15, 25]
str = [0]
dex = [0]
int = [18, 23]
vit = [10, 13]

[shoes.light.epic]
armour = [18, 28]
magic = [16, 26]
str = [0]
dex = [0]
int = [19, 25]
vit = [10, 13]

[shoes.light.legendary]
armour = [18, 28]
magic = [16, 26]
str = [0]
dex = [0]
int = [19, 25]
vit = [15, 20]

# Cloak
[cloak.rare]
armour = [21, 31]
magic = [17, 27]
str = [18, 23]
dex = [18, 23]
int = [18, 23]
vit = [18, 23]

[cloak.epic]
armour = [22, 32]
magic = [18, 28]
str = [19, 25]
dex = [19, 25]
int = [19, 25]
vit = [19, 25]

[cloak.legendary]
armour = [22, 32]
magic = [20, 30]
str = [19, 25]
dex = [19, 25]
int = [19, 25]
vit = [19, 25]

# Hand
## Shield
[shield.rare]
armour = [23, 33]
magic = [23, 33]
str = [0]
dex = [0]
int = [0]
vit = [17, 22]

[shield.epic]
armour = [24, 34]
magic = [24, 34]
str = [0]
dex = [0]
int = [0]
vit = [18, 23]

[shield.legendary]
armour = [25, 35]
magic = [25, 35]
str = [0]
dex = [0]
int = [0]
vit = [21, 27]

## Melee
### Sword
[melee.sword.rare]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.sword.epic]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.sword.legendary]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

### Axe
[melee.axe.rare]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.axe.epic]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.axe.legendary]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

### Greatsword
[melee.greatsword.rare]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.greatsword.epic]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.greatsword.legendary]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

### GreatAxe
[melee.greataxe.rare]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.greataxe.epic]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[melee.greataxe.legendary]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

## Bow
[bow.bow.rare]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[bow.bow.epic]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[bow.bow.legendary]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

## Staff
[staff.staff.rare]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[staff.staff.epic]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

[staff.staff.legendary]
damage = [["???", "???"], ["???", "???"]]
speed = ["???"]
primary = ["???", "???"]
secondary = ["???", "???"]
normal = ["???", "???"]

