#############
# Format
## Armour (inc. shields & cloak)
# [<slot>.<heavy/medium/light>.<rarity>]
# <stat> = [<new gear value>, <maxed value>]
## Weapon
# [<melee/bow/staff>.<type>.<rarity>]
# <stat> = [<new gear value>, <maxed value>]
#
# Tips
# If you're trying to find something, search for it!
#############

# Head
## Heavy
[head.heavy.rare]
armour = [12, 22]
magic = [11, 12]
str = [5, 6]
dex = [0, 0]
int = [0, 0]
vit = [5, 6]

[head.heavy.epic]
armour = [13, 23]
magic = [12, 22]
str = [5, 6]
dex = [0, 0]
int = [0, 0]
vit = [5, 6]

[head.heavy.legendary]
armour = [18, 28]
magic = [12, 22]
str = [7, 9]
dex = [0, 0]
int = [0, 0]
vit = [7, 9]

## Medium
[head.medium.rare]
armour = [7, 17]
magic = [7, 17]
str = [0, 0]
dex = [5, 6]
int = [0, 0]
vit = [5, 6]

[head.medium.epic]
armour = [8, 18]
magic = [8, 18]
str = [0, 0]
dex = [5, 6]
int = [0, 0]
vit = [5, 6]

[head.medium.legendary]
armour = [10, 20]
magic = [6, 16]
str = [0, 0]
dex = [7, 9]
int = [0, 0]
vit = [5, 6]

## Light
[head.light.rare]
armour = [5, 15]
magic = [6, 16]
str = [0, 0]
dex = [0, 0]
int = [5, 6]
vit = [5, 6]

[head.light.epic]
armour = [5, 15]
magic = [7, 17]
str = [0, 0]
dex = [0, 0]
int = [5, 6]
vit = [6, 8]

[head.light.legendary]
armour = [6, 16]
magic = [5, 15]
str = [0, 0]
dex = [0, 0]
int = [7, 9]
vit = [4, 5]

# Shoulders
## Heavy
[shoulders.heavy.rare]
armour = [12, 22]
magic = [11, 21]
str = [5, 6]
dex = [0, 0]
int = [0, 0]
vit = [5, 6]

[shoulders.heavy.epic]
armour = [13, 23]
magic = [12, 22]
str = [5, 6]
dex = [0, 0]
int = [0, 0]
vit = [5, 6]

[shoulders.heavy.legendary]
armour = [18, 28]
magic = [12, 22]
str = [7, 9]
dex = [0, 0]
int = [0, 0]
vit = [7, 9]

## Medium
[shoulders.medium.rare]
armour = [9, 19]
magic = [7, 17]
str = [0, 0]
dex = [5, 6]
int = [0, 0]
vit = [5, 6]

[shoulders.medium.epic]
armour = [10, 20]
magic = [8, 18]
str = [0, 0]
dex = [5, 6]
int = [0, 0]
vit = [5, 6]

[shoulders.medium.legendary]
armour = [10, 20]
magic = [6, 16]
str = [0, 0]
dex = [7, 9]
int = [0, 0]
vit = [6, 8]

## Light
[shoulders.light.rare]
armour = [6, 16]
magic = [6, 16]
str = [0, 0]
dex = [0, 0]
int = [5, 6]
vit = [5, 6]

[shoulders.light.epic]
armour = [7, 17]
magic = [7, 17]
str = [0, 0]
dex = [0, 0]
int = [5, 6]
vit = [6, 8]

[shoulders.light.legendary]
armour = [7, 17]
magic = [5, 15]
str = [0, 0]
dex = [0, 0]
int = [7, 9]
vit = [5, 6]

# Chest
## Heavy
[chest.heavy.rare]
armour = [14, 24]
magic = [12, 22]
str = [6, 8]
dex = [0, 0]
int = [0, 0]
vit = [6, 8]

[chest.heavy.epic]
armour = [16, 26]
magic = [14, 24]
str = [6, 8]
dex = [0, 0]
int = [0, 0]
vit = [7, 9]

[chest.heavy.legendary]
armour = [20, 30]
magic = [15, 25]
str = [9, 12]
dex = [0, 0]
int = [0, 0]
vit = [10, 13]

## Medium
[chest.medium.rare]
armour = [11, 21]
magic = [10, 20]
str = [0, 0]
dex = [6, 8]
int = [0, 0]
vit = [5, 6]

[chest.medium.epic]
armour = [12, 22]
magic = [11, 21]
str = [0, 0]
dex = [6, 8]
int = [0, 0]
vit = [6, 8]

[chest.medium.legendary]
armour = [12, 22]
magic = [8, 18]
str = [0, 0]
dex = [9, 12]
int = [0, 0]
vit = [8, 10]

## Light
[chest.light.rare]
armour = [7, 17]
magic = [7, 17]
str = [0, 0]
dex = [0, 0]
int = [6, 8]
vit = [5, 6]

[chest.light.epic]
armour = [7, 17]
magic = [8, 18]
str = [0, 0]
dex = [0, 0]
int = [6, 8]
vit = [6, 8]

[chest.light.legendary]
armour = [9, 19]
magic = [6, 16]
str = [0, 0]
dex = [0, 0]
int = [9, 12]
vit = [6, 8]

# Legs
## Heavy
[legs.heavy.rare]
armour = [14, 24]
magic = [12, 22]
str = [6, 8]
dex = [0, 0]
int = [0, 0]
vit = [6, 8]

[legs.heavy.epic]
armour = [16, 26]
magic = [14, 24]
str = [6, 8]
dex = [0, 0]
int = [0, 0]
vit = [7, 9]

[legs.heavy.legendary]
armour = [20, 30]
magic = [15, 25]
str = [9, 12]
dex = [0, 0]
int = [0, 0]
vit = [10, 13]

## Medium
[legs.medium.rare]
armour = [11, 21]
magic = [10, 20]
str = [0, 0]
dex = [6, 8]
int = [0, 0]
vit = [5, 6]

[legs.medium.epic]
armour = [12, 22]
magic = [11, 21]
str = [0, 0]
dex = [6, 8]
int = [0, 0]
vit = [6, 8]

[legs.medium.legendary]
armour = [12, 22]
magic = [8, 18]
str = [0, 0]
dex = [9, 12]
int = [0, 0]
vit = [7, 9]

## Light
[legs.light.rare]
armour = [7, 17]
magic = [7, 17]
str = [0, 0]
dex = [0, 0]
int = [6, 8]
vit = [5, 6]

[legs.light.epic]
armour = [7, 17]
magic = [8, 18]
str = [0, 0]
dex = [0, 0]
int = [6, 8]
vit = [6, 8]

[legs.light.legendary]
armour = [9, 19]
magic = [6, 16]
str = [0, 0]
dex = [0, 0]
int = [9, 12]
vit = [6, 8]

# Gloves
## Heavy
[gloves.heavy.rare]
armour = [10, 20]
magic = [10, 20]
str = [5, 6]
dex = [0, 0]
int = [0, 0]
vit = [5, 6]

[gloves.heavy.epic]
armour = [11, 21]
magic = [11, 21]
str = [5, 6]
dex = [0, 0]
int = [0, 0]
vit = [5, 6]

[gloves.heavy.legendary]
armour = [16, 26]
magic = [12, 22]
str = [6, 8]
dex = [0, 0]
int = [0, 0]
vit = [6, 8]

## Medium
[gloves.medium.rare]
armour = [7, 17]
magic = [5, 15]
str = [0, 0]
dex = [5, 6]
int = [0, 0]
vit = [5, 6]

[gloves.medium.epic]
armour = [8, 18]
magic = [6, 16]
str = [0, 0]
dex = [5, 6]
int = [0, 0]
vit = [5, 6]

[gloves.medium.legendary]
armour = [8, 18]
magic = [4, 14]
str = [0, 0]
dex = [6, 8]
int = [0, 0]
vit = [5, 6]

## Light
[gloves.light.rare]
armour = [5, 15]
magic = [5, 15]
str = [0, 0]
dex = [0, 0]
int = [5, 6]
vit = [5, 6]

[gloves.light.epic]
armour = [5, 15]
magic = [6, 16]
str = [0, 0]
dex = [0, 0]
int = [5, 6]
vit = [6, 8]

[gloves.light.legendary]
armour = [6, 16]
magic = [4, 14]
str = [0, 0]
dex = [0, 0]
int = [6, 8]
vit = [4, 5]

# Shoes
## Heavy
[shoes.heavy.rare]
armour = [10, 20]
magic = [10, 20]
str = [5, 6]
dex = [0, 0]
int = [0, 0]
vit = [5, 6]

[shoes.heavy.epic]
armour = [11, 21]
magic = [11, 21]
str = [5, 6]
dex = [0, 0]
int = [0, 0]
vit = [5, 6]

[shoes.heavy.legendary]
armour = [16, 26]
magic = [12, 22]
str = [6, 8]
dex = [0, 0]
int = [0, 0]
vit = [6, 8]

## Medium
[shoes.medium.rare]
armour = [7, 17]
magic = [5, 15]
str = [0, 0]
dex = [5, 6]
int = [0, 0]
vit = [5, 6]

[shoes.medium.epic]
armour = [8, 18]
magic = [6, 16]
str = [0, 0]
dex = [5, 6]
int = [0, 0]
vit = [5, 6]

[shoes.medium.legendary]
armour = [8, 18]
magic = [4, 14]
str = [0, 0]
dex = [6, 8]
int = [0, 0]
vit = [5, 6]

## Light
[shoes.light.rare]
armour = [5, 15]
magic = [5, 15]
str = [0, 0]
dex = [0, 0]
int = [5, 6]
vit = [5, 6]

[shoes.light.epic]
armour = [5, 15]
magic = [6, 16]
str = [0, 0]
dex = [0, 0]
int = [5, 6]
vit = [6, 8]

[shoes.light.legendary]
armour = [6, 16]
magic = [4, 14]
str = [0, 0]
dex = [0, 0]
int = [6, 8]
vit = [4, 5]

# Cloak
[cloak.rare]
armour = ["3?", "13?"]
magic = ["3?", "13?"]
str = ["9?", "12?"]
dex = ["8?", "11?"]
int = ["8?", "11?"]
vit = ["9?", "12?"]

[cloak.epic]
armour = ["2?", "12?"]
magic = ["3?", "13?"]
str = ["11?", "???"]
dex = ["9?", "???"]
int = ["11?", "???"]
vit = ["11?", "???"]

[cloak.legendary]
armour = [5, 15]
magic = [4, 14]
str = [9, 12]
dex = [9, 12]
int = [9, 12]
vit = [9, 12]

# Hand
## Shield
[shield.rare]
armour = [8, 18]
magic = [7, 17]
str = [0, 0]
dex = [0, 0]
int = [0, 0]
vit = [5, 6]

[shield.epic]
armour = [8, 18]
magic = [8, 18]
str = [0, 0]
dex = [0, 0]
int = [0, 0]
vit = [5, 6]

[shield.legendary]
armour = [12, 22]
magic = [10, 20]
str = [0, 0]
dex = [0, 0]
int = [0, 0]
vit = [9, 12]

## Melee
### Sword
[melee.sword.rare]
damage = [["12?", "14?"], ["22?", "24?"]]
speed = ["2.3?", "2.3?"]
primary = ["12?", "15?"]
secondary = ["12?", "15?"]
normal = ["12?", "15?"]

str = ["10?", "13?"]
dex = ["12?", "15?"]
int = ["12?", "15?"]
vit = ["12?", "15?"]

[melee.sword.epic]
damage = [["10?", "12?"], ["20?", "22?"]]
speed = ["2.6?", "2.6?"]
normal = ["10?", "11?"]
primary = ["12?", "13?"]
secondary = ["10?", "11?"]

str = ["10?", "11?"]
dex = ["9?", "10?"]
int = ["12?", "13?"]
vit = ["10?", "11?"]

[melee.sword.legendary]
damage = [["12?", "14?"], ["22?", "24?"]]
speed = ["2.42?", "2.42?"]
normal = ["10?", "???"]
primary = ["12?", "???"]
secondary = ["10?", "???"]

str = ["10?", "???"]
dex = ["9?", "???"]
int = ["12?", "???"]
vit = ["10?", "???"]

### Axe
# NOTE - Has +12 max in primary scaling?
[melee.axe.rare]
damage = [["13?", "15?"], ["23?", "25?"]]
speed = ["2.52?", "2.52?"]
primary = ["12?", "15?"]
secondary = ["12?", "15?"]
normal = ["12?", "15?"]

str = ["12?", "15?"]
dex = ["10?", "13?"]
int = ["12?", "15?"]
vit = ["12?", "15?"]

[melee.axe.epic]
damage = [["12?", "14?"], ["22?", "24?"]]
speed = ["2.54?", "2.54?"]
primary = ["10?", "???"]
secondary = ["10?", "???"]
normal = ["10?", "???"]

str = ["10?", "???"]
dex = ["10?", "???"]
int = ["10?", "???"]
vit = ["9?", "???"]

[melee.axe.legendary]
damage = [["13?", "15?"], ["21?", "23?"]]
speed = ["2.53?", "2.53?"]
primary = ["12?", "14?"]
secondary = ["12?", "14?"]
normal = ["10?", "12?"]

str = ["9?", "12?"]
dex = ["12?", "14?"]
int = ["12?", "14?"]
vit = ["10?", "12?"]

### Greatsword
[melee.greatsword.rare]
damage = [["18?", "21?"], ["28?", "31?"]]
speed = ["3.03?", "3.03?"]
secondary = ["15?", "19"]
normal = ["15?", "???"]
primary = ["16?", "???"]

str = ["15?", "19"]
dex = ["15?", "???"]
int = ["16?", "???"]
vit = ["14?", "???"]

[melee.greatsword.epic]
damage = [["14?", "17?"], ["24?", "27?"]]
speed = ["3.39?", "3.39?"]
primary = ["13?", "???"]
secondary = ["12?", "???"]
normal = ["12?", "???"]

str = ["12?", "???"]
dex = ["10?", "???"]
int = ["12?", "???"]
vit = ["13?", "???"]

[melee.greatsword.legendary]
damage = [["18?", "21?"], ["28?", "31?"]]
speed = ["3.08?", "3.08?"]
primary = ["16?", "???"]
secondary = ["16?", "???"]
normal = ["16?", "???"]

str = ["16?", "???"]
dex = ["14?", "???"]
int = ["16?", "???"]
vit = ["16?", "???"]

### GreatAxe
[melee.greataxe.rare]
damage = [["20?", "23?"], ["29?", "32?"]]
speed = ["3.3?", "3.3?"]
primary = ["16?", "???"]
secondary = ["16?", "???"]
normal = ["16?", "???"]

str = ["16?", "???"]
dex = ["16?", "???"]
int = ["16?", "???"]
vit = ["16?", "???"]

[melee.greataxe.epic]
damage = [["17?", "20?"], ["26?", "29?"]]
speed = ["3.33?", "3.33?"]
primary = ["16?", "20?"]
secondary = ["14?", "18?"]
normal = ["14?", "14?"]

str = ["16?", "20?"]
dex = ["13?", "14?"]
int = ["14?", "14?"]
vit = ["14?", "18?"]

[melee.greataxe.legendary]
damage = [["18?", "21?"], ["26?", "29?"]]
speed = ["3.47?", "3.47?"]
primary = ["16?", "???"]
secondary = ["16?", "???"]
normal = ["14?", "???"]

str = ["13?", "???"]
dex = ["16?", "???"]
int = ["14?", "???"]
vit = ["16?", "???"]

## Bow
[bow.bow.rare]
damage = [["20?", "23?"], ["30?", "33?"]]
speed = ["3.02?", "3.02?"]
primary = ["16?", "???"]
secondary = ["16?", "???"]
normal = ["16?", "???"]

str = ["16?", "???"]
dex = ["16?", "???"]
int = ["16?", "???"]
vit = ["13?", "???"]

[bow.bow.epic]
damage = [["18?", "21?"], ["28?", "31?"]]
speed = ["3.31?", "3.31?"]
primary = ["15?", "???"]
secondary = ["14?", "???"]
normal = ["14?", "???"]

str = ["14?", "???"]
dex = ["13?", "???"]
int = ["14?", "???"]
vit = ["15?", "???"]

[bow.bow.legendary]
damage = [["20?", "23?"], ["30?", "33?"]]
speed = ["3.02?", "3.02?"]
primary = ["16?", "???"]
secondary = ["12?", "???"]
normal = ["12?", "???"]

str = ["12?", "???"]
dex = ["12?", "???"]
int = ["12?", "???"]
vit = ["16?", "???"]

## Staff
[staff.staff.rare]
damage = [["17?", "20?"], ["27?", "30?"]]
speed = ["3.07?", "3.07?"]
primary = ["16?", "???"]
secondary = ["16?", "???"]
normal = ["16?", "???"]

str = ["16?", "???"]
dex = ["16?", "???"]
int = ["16?", "???"]
vit = ["15?", "???"]

[staff.staff.epic]
damage = [["20?", "23?"], ["26?", "29?"]]
speed = ["3.09?", "3.09?"]
primary = ["16?", "???"]
secondary = ["15?", "???"]
normal = ["15?", "???"]

str = ["15?", "???"]
dex = ["15?", "???"]
int = ["15?", "???"]
vit = ["16?", "???"]

[staff.staff.legendary]
damage = [["17?", "20?"], ["27?", "30?"]]
speed = ["3.36?", "3.36?"]
primary = ["15?", "???"]
secondary = ["15?", "???"]
normal = ["14?", "???"]

str = ["14?", "???"]
dex = ["13?", "???"]
int = ["15?", "???"]
vit = ["15?", "???"]

