[[active]]
note = "Granted with the release of Guild Dominion"
code = "AL888"
available = 2025-08-01
diamonds = 1000
gold = 70_000
tokens = 200

[[active.materials]]
rarity = "Gold Bar"
count = 100
[[active.materials]]
rarity = "Iron Bar"
count = 100
[[active.materials]]
rarity = "Red Bar"
count = 100

[[expired]]
note = "Granted for gaining 100 players at 5+ ELO before Christmas"
code = "ALXMAS"
gold = 200_000
diamonds = 500
title = "Kindred Spirit"
tokens = 100
synergy_stones = 20
# available = 2024-12-24
expire = 2025-01-01

[[expired.materials]]
rarity = "Epic"
count = 20
[[expired.materials]]
rarity = "Legendary"
count = 5

[[active]]
code = "AL777"
diamonds = 500
gold = 50_000
#expire = 2025-01-01
# activated_again = 2025-01-05

[[expired]]
note = "Granted to internal testers for their hard work"
code = "ALTESTER"
gold = 100_000
diamonds = 1_000
tokens = 100
title = "Infernal Fester"
expire = 2024-12-08

[[expired.items]]
name = "Demon Herald's Cloak"
rarity = "Legendary"
slot = "Cloak"
cosmetic = "Red Wings"
count = 1

[[expired.items]]
rarity = "Epic"
count = 3
