expired = []

[[active]]
code = "AL777"
diamonds = 500
gold = 50_000

[[active]]
note = "Granted to internal testers for their hard work"
code = "[REDACTED]"
gold = 100_000
diamonds = 1_000
tokens = 100
title = "Infernal Fester"

[[active.items]]
name = "Demon Herald's Cloak"
rarity = "Legendary"
slot = "Cloak"
cosmetic = "Red Wings"
count = 1

[[active.items]]
rarity = "Epic"
count = 3

[[future]]
note = "Granted if the Christmas goal is reached"
code = "Christmas"
gold = 200_000
diamonds = 500
title = "Kindred Spirit"
